name: Test marketplace action
  uses:  simple-elf/allure-report-action@master
  if: always()
  id: allure-report
  with:
    allure_results: build/allure-results
    gh_pages: gh-pages
    allure_report: allure-report
    allure_history: allure-history
